require'globals'
require'requirements'
require'plugins'
require'settings'
require'keymaps'
require'mycmp'
require'myfonts'
require'myneotree'
require'mytreesitter'
require'mypyright'
require'myelixir'
require'mytab'
require'myhop'
require'mydap'
require'myautocmds'
-- require'mycmpdelay'
